version: '3'
services:
  db:
    build: ./db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'salesman'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'